import type { AppSettings, Task, Announcement } from '../types/index.ts';

export const DEFAULT_SETTINGS: AppSettings = {
  minWithdrawalCoins: 500, // 500 coins = ₹5.00
  coinToCurrencyRatio: 100, // 100 coins = 1 unit (₹1.00)
  currencySymbol: '₹',
  referralRewardCoins: 100, // Inviter earns 100 coins
  referralJoinBonusCoins: 50, // Invitee earns 50 coins
  dailyAdLimit: 10,
  adRewardCoins: 25,
  dailyBonusCoins: 15,
  dailyBonusMinCoins: 10,
  dailyBonusMaxCoins: 50,
  checkInRewards: [10, 15, 20, 25, 35, 50, 100],
  supportEmail: 'support@freeearn.app',
  supportWhatsapp: '+91 9113124207',
  admobAppId: 'ca-app-pub-7524191132114722~4422067441',
  admobRewardedUnitId: 'ca-app-pub-7524191132114722/4622212147',
  admobBannerUnitId: 'ca-app-pub-7524191132114722/4622212147',

  // Master Feature Controls
  maintenanceMode: false,
  maintenanceMessage: 'Free Earn app is undergoing scheduled system optimization. All user coin balances and pending withdrawals are 100% safe. We will be back online shortly!',
  dailyCheckInEnabled: true,
  dailyBonusEnabled: true,
  videoAdsEnabled: true,
  adCooldownSeconds: 30,
  tasksEnabled: true,
  referralEnabled: true,
  withdrawalsEnabled: true,
  withdrawalsDisabledReason: 'Withdrawals are momentarily paused for banking reconciliation. Please check back in a few hours.',
  allowedWithdrawalMethods: ['upi', 'bank', 'paytm', 'phonepe'],
  homeNoticeActive: false,
  homeNoticeText: '⚡ All UPI payouts are processing within 2 hours today! Complete tasks to earn extra bonus coins.',
};

export const INITIAL_TASKS: Omit<Task, 'id' | 'createdAt'>[] = [
  {
    title: 'Install & Register: BHIM UPI App',
    description: 'Download the official BHIM UPI app, register with your bank mobile number, and complete 1st UPI setup to earn instant coins.',
    rewardCoins: 350,
    category: 'app',
    instructions: '1. Click open link to download BHIM from official link.\n2. Complete mobile number verification.\n3. Link your bank account and make 1 test transfer or scan QR.\n4. Submit your registered UPI ID/screenshot as proof.',
    stepGuide: [
      'Download & install BHIM app',
      'Register mobile & link bank account',
      'Submit your BHIM UPI ID as proof'
    ],
    dailyLimit: 1000,
    status: 'active',
    badge: 'Featured UPI',
    externalUrl: 'https://bhim.onelink.me/CoHB/dr3s0al0',
    verificationMethod: 'proof_link',
  },
];

export const INITIAL_ANNOUNCEMENTS: Omit<Announcement, 'id' | 'createdAt'>[] = [
  {
    title: '⚡ Instant UPI Withdrawals Active!',
    message: 'All withdrawal requests are processed within 2 to 24 hours. Make sure your UPI ID is linked to your primary bank account.',
    badge: 'Update',
    priority: 'high',
    active: true,
  },
  {
    title: '🎁 Refer & Earn 100 Coins Per Friend',
    message: 'Share your referral code! When your friend joins, they get 50 bonus coins and you get 100 coins after their first task.',
    badge: 'Bonus',
    priority: 'normal',
    active: true,
  },
  {
    title: '🛡️ Anti-Fraud & Fair Play Policy',
    message: 'Multiple accounts on a single device or automated clickers result in immediate permanent account termination.',
    badge: 'Security',
    priority: 'normal',
    active: true,
  },
];

// Rich Demo Data for 100% Standalone Simulation
import type { UserProfile, TaskSubmission, Transaction, Withdrawal } from '../types/index.ts';

export const DEMO_USERS: UserProfile[] = [
  {
    uid: 'user_demo_vikram',
    name: 'Vikram Singh',
    mobile: '+91 98111 22334',
    email: 'vikram.singh@example.com',
    referralCode: 'VIKRAM01',
    coins: 450,
    todayEarnings: 50,
    totalEarnings: 600,
    totalWithdrawn: 150,
    pendingWithdrawalCoins: 0,
    level: 'Silver',
    isBlocked: false,
    consecutiveCheckIns: 2,
    adsWatchedToday: 1,
    createdAt: '2026-10-01T00:00:00.000Z',
    isAdmin: false,
  },
  {
    uid: 'user_demo_rahul',
    name: 'Rahul Sharma',
    mobile: '+91 98765 12345',
    email: 'rahul.sharma@example.com',
    referralCode: 'RAHUL99',
    referredBy: 'ANKUSH07',
    coins: 650,
    todayEarnings: 75,
    totalEarnings: 850,
    totalWithdrawn: 200,
    pendingWithdrawalCoins: 0,
    level: 'Silver',
    isBlocked: false,
    consecutiveCheckIns: 3,
    adsWatchedToday: 2,
    createdAt: '2026-09-28T10:00:00.000Z',
    isAdmin: false,
  },
  {
    uid: 'user_demo_priya',
    name: 'Priya Verma',
    mobile: '+91 98123 45678',
    email: 'priya.earn@example.com',
    referralCode: 'PRIYA01',
    referredBy: 'ANKUSH07',
    coins: 1420,
    todayEarnings: 210,
    totalEarnings: 2200,
    totalWithdrawn: 500,
    pendingWithdrawalCoins: 280,
    level: 'Platinum',
    isBlocked: false,
    consecutiveCheckIns: 6,
    adsWatchedToday: 5,
    createdAt: '2026-09-25T14:30:00.000Z',
    isAdmin: false,
  },
  {
    uid: 'user_demo_amit',
    name: 'Amit Patel',
    mobile: '+91 97234 56789',
    email: 'amit.patel@example.com',
    referralCode: 'AMIT88',
    coins: 320,
    todayEarnings: 20,
    totalEarnings: 320,
    totalWithdrawn: 0,
    pendingWithdrawalCoins: 0,
    level: 'Bronze',
    isBlocked: false,
    consecutiveCheckIns: 1,
    adsWatchedToday: 1,
    createdAt: '2026-09-30T09:15:00.000Z',
    isAdmin: false,
  },
];

export const DEMO_TRANSACTIONS: Transaction[] = [
  {
    id: 'txn_init_bonus_ankush',
    userId: 'user_phone_9113124207',
    type: 'daily_bonus',
    amountCoins: 1000,
    amountCurrency: 10.0,
    status: 'completed',
    description: 'Welcome Bonus for Registered User +91 9113124207',
    createdAt: '2026-10-01T00:00:00.000Z',
  },
  {
    id: 'txn_demo_rahul_referral',
    userId: 'user_phone_9113124207',
    type: 'referral_bonus',
    amountCoins: 100,
    amountCurrency: 1.0,
    status: 'completed',
    description: 'Referral bonus from friend Rahul Sharma',
    createdAt: '2026-09-28T12:00:00.000Z',
  },
  {
    id: 'txn_demo_priya_referral',
    userId: 'user_phone_9113124207',
    type: 'referral_bonus',
    amountCoins: 100,
    amountCurrency: 1.0,
    status: 'completed',
    description: 'Referral bonus from friend Priya Verma',
    createdAt: '2026-09-25T16:00:00.000Z',
  },
];

export const DEMO_SUBMISSIONS: TaskSubmission[] = [
  {
    id: 'sub_demo_priya_fintech',
    taskId: 'task_fintech_app',
    taskTitle: 'Install & Register: Fintech Savings App',
    userId: 'user_demo_priya',
    userName: 'Priya Verma',
    userMobile: '+91 98123 45678',
    rewardCoins: 250,
    proofLink: 'https://drive.google.com/sample-screenshot.png',
    proofNotes: 'Registered with phone 9812345678. OTP completed successfully.',
    status: 'pending',
    submittedAt: '2026-10-01T01:15:00.000Z',
  },
  {
    id: 'sub_demo_rahul_survey',
    taskId: 'task_survey_consumer',
    taskTitle: 'Complete 3-Min Consumer Trends Survey',
    userId: 'user_demo_rahul',
    userName: 'Rahul Sharma',
    userMobile: '+91 98765 12345',
    rewardCoins: 180,
    proofLink: 'SURVEY-CONF-98213',
    proofNotes: 'Survey completion confirmation code: CONF-98213',
    status: 'approved',
    adminNotes: 'Verified with survey response database.',
    submittedAt: '2026-09-30T18:20:00.000Z',
    reviewedAt: '2026-09-30T19:00:00.000Z',
  },
];

export const DEMO_WITHDRAWALS: Withdrawal[] = [
  {
    id: 'wd_demo_priya_upi',
    userId: 'user_demo_priya',
    userName: 'Priya Verma',
    userMobile: '+91 98123 45678',
    amountCoins: 280,
    amountCurrency: 2.8,
    method: 'upi',
    upiId: 'priyaverma@okaxis',
    status: 'pending',
    requestedAt: '2026-10-01T01:45:00.000Z',
  },
  {
    id: 'wd_demo_rahul_paid',
    userId: 'user_demo_rahul',
    userName: 'Rahul Sharma',
    userMobile: '+91 98765 12345',
    amountCoins: 200,
    amountCurrency: 2.0,
    method: 'upi',
    upiId: 'rahul99@oksbi',
    status: 'paid',
    requestedAt: '2026-09-29T11:00:00.000Z',
    processedAt: '2026-09-29T12:30:00.000Z',
    txnHash: 'UPI/2638192837/SUCCESS',
  },
];
